import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import type { Policy, AuditReport } from '@shared/schema';

export async function generatePolicyPDF(policy: Policy): Promise<string> {
  const doc = new PDFDocument();
  const filename = `policy-${policy.id}-${Date.now()}.pdf`;
  const filepath = path.join(process.cwd(), 'generated-pdfs', filename);

  // Ensure directory exists
  const dir = path.dirname(filepath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text('RegReady Compliance Platform', { align: 'center' });
  doc.moveDown();
  
  // Policy title
  doc.fontSize(18).text(policy.title, { align: 'center' });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Policy Type: ${policy.type}`);
  doc.text(`Version: ${policy.version}`);
  doc.text(`Status: ${policy.status}`);
  doc.text(`Created: ${policy.createdAt.toLocaleDateString()}`);
  doc.text(`Last Updated: ${policy.updatedAt.toLocaleDateString()}`);
  
  if (policy.frameworks && policy.frameworks.length > 0) {
    doc.text(`Compliance Frameworks: ${policy.frameworks.join(', ')}`);
  }
  
  doc.moveDown();

  // Description
  if (policy.description) {
    doc.fontSize(14).text('Description', { underline: true });
    doc.fontSize(12).text(policy.description);
    doc.moveDown();
  }

  // Content
  if (policy.content) {
    doc.fontSize(14).text('Policy Content', { underline: true });
    doc.fontSize(12).text(policy.content);
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}

export async function generateAuditReportPDF(report: AuditReport): Promise<string> {
  const doc = new PDFDocument();
  const filename = `audit-report-${report.id}-${Date.now()}.pdf`;
  const filepath = path.join(process.cwd(), 'generated-pdfs', filename);

  // Ensure directory exists
  const dir = path.dirname(filepath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc.fontSize(20).text('RegReady Compliance Audit Report', { align: 'center' });
  doc.moveDown();
  
  // Report title
  doc.fontSize(18).text(report.title, { align: 'center' });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Report Type: ${report.type}`);
  if (report.framework) {
    doc.text(`Framework: ${report.framework}`);
  }
  doc.text(`Status: ${report.status}`);
  doc.text(`Generated: ${report.generatedAt.toLocaleDateString()}`);
  doc.text(`Generated By: ${report.generatedBy}`);
  doc.moveDown();

  // Executive Summary
  if (report.summary) {
    doc.fontSize(14).text('Executive Summary', { underline: true });
    doc.fontSize(12).text(report.summary);
    doc.moveDown();
  }

  // Findings
  if (report.findings && report.findings.length > 0) {
    doc.fontSize(14).text('Key Findings', { underline: true });
    doc.fontSize(12);
    report.findings.forEach((finding, index) => {
      doc.text(`${index + 1}. ${typeof finding === 'string' ? finding : JSON.stringify(finding)}`);
    });
    doc.moveDown();
  }

  // Recommendations
  if (report.recommendations && report.recommendations.length > 0) {
    doc.fontSize(14).text('Recommendations', { underline: true });
    doc.fontSize(12);
    report.recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`);
    });
    doc.moveDown();
  }

  // Footer
  doc.fontSize(10).text(
    `Generated by RegReady on ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}
